import type { Metadata } from "next"
import { Inter } from "next/font/google"

import { TanstackProviders } from "@/provider/query-provider"
import SessionProvider from "@/provider/session-provider"
import { ThemeProvider } from "@/provider/theme-provider"

import "@/styles/global.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Next App Router Template",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <TanstackProviders>
          <SessionProvider>
            <ThemeProvider>{children}</ThemeProvider>
          </SessionProvider>
        </TanstackProviders>
      </body>
    </html>
  )
}
